In [7]:
# Create a NumPy array containing integers from 1 to 10.

import numpy as np

arr =  np.array([1,2,3,4,5,6,7,8,9,10])

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
# Create a 2D NumPy array with shape (3, 4) filled with random float values between 0 and 1.

random_array = np.random.rand(3, 4)

print(random_array)

[[0.60664362 0.61804254 0.62651185 0.93785639]
 [0.57936961 0.64924798 0.11884568 0.54180063]
 [0.57054716 0.0250936  0.99739244 0.26958332]]


In [3]:
# Given the following NumPy array: arr = np.array([10, 20, 30, 40, 50]) Add 5 to each element of the array.

arr = np.array([10, 20, 30, 40, 50])

arr+5

array([15, 25, 35, 45, 55])

In [5]:
# Given two NumPy arrays: arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8]) Concatenate them into a single array

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

single_array = np.hstack((arr1,arr2))

single_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# Create a NumPy array of 10 elements with equally spaced values from 0 to 9.

equally_spaced_array = np.arange(10)

print(equally_spaced_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Given a NumPy array: arr = np.array([1, 2, 3, 4, 5, 6]) Reverse the elements in the array.

arr = np.array([1, 2, 3, 4, 5, 6]) 

arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [9]:
# Create a 3x3 identity matrix using NumPy.

identity_matrix = np.identity(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Calculate the mean, median, and standard deviation of the following NumPy array: arr = np.array([15, 20, 25, 30, 35])

arr = np.array([15, 20, 25, 30, 35])

arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)

print(arr_mean)
print(arr_median)
print(arr_std)



25.0
25.0
7.0710678118654755


In [35]:
# Given a 2D NumPy array:arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) Get the diagonal elements of the array.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_diagonal = np.diagonal(arr)

arr_diagonal

array([1, 5, 9])

In [36]:
# Create a NumPy array of 10 random integers between 1 and 100 (inclusive).

arr = np.random.randint(1,101, size=10)

arr

array([12, 80, 88, 42, 11, 87, 46, 56, 20, 16])

In [37]:
# Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 50 (inclusive).

random_integers_array = np.random.randint(1, 51, size=(5, 5))

random_integers_array

array([[22, 25, 49, 13, 42],
       [40,  2, 14, 40, 24],
       [50,  6, 33, 19, 47],
       [17, 10, 38, 11, 22],
       [11, 28, 16, 21, 31]])

In [39]:
# Given a 2D NumPy array: arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) Calculate the sum of all the elements in the array.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_sum = np.sum(arr)
arr_sum

45

In [44]:
# Create a NumPy array with 100 evenly spaced values between 0 and 1 (inclusive) and reshape it into a 10x10 matrix.

evenly_spaced_array = np.linspace(0, 1, num=100)
reshaped_matrix = evenly_spaced_array.reshape(10, 10)
reshaped_matrix

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [48]:
# Given two NumPy arrays: import numpy as np arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8]) Find the common elements between the two arrays.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

common_elements = np.intersect1d(arr1, arr2)

#There is no common element so output will be []
list(common_elements)


[]

In [50]:
# Create a NumPy array containing 10 random integers between -50 and 50 (inclusive). Replace all negative values in the array with 0.
random_integers = np.random.randint(-50, 51, size=10)

random_integers[random_integers < 0] = 0

random_integers

array([ 8, 43, 21,  0,  0,  0, 46,  0,  0,  0])

In [5]:
# Given a 2D NumPy array: import numpy as np arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) Calculate the sum of each row and each column separately

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_sums = np.sum(arr, axis=1)

col_sums = np.sum(arr, axis = 0)

print(row_sums)
print(col_sums)

[ 6 15 24]
[12 15 18]


In [9]:
# Create a NumPy array of shape (6, 6) with diagonal elements as 1, 2, 3, 4, 5, and 6, and all other elements as 0.

diagonal_elements = np.array([1,2,3,4,5,6])
diagonal_matrix = np.diag(diagonal_elements)

diagonal_matrix

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [11]:
# Given a NumPy array: import numpy as np arr = np.array([1, 2, 3, 4, 5]) Normalize the array so that the values range from 0 to 1.

# formula for normalized_value = (x - min) / (max - min) where x is the orginal value

arr = np.array([1, 2, 3, 4, 5])

min_value = np.min(arr)
max_value = np.max(arr)

normalized_arr = (arr - min_value)/(max_value - min_value)

normalized_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Create a NumPy array with 20 random integers between 1 and 100 (inclusive). Find the maximum value and its index in the array.

random_integers = np.random.randint(1,101, size=20)

max_value = np.max(random_integers)
max_index = np.argmax(random_integers)

print("Array:", random_integers)
print("Maximum value:", max_value)
print("Index of maximum value:", max_index)

Array: [53 89 11 65 82 63 61 19 65 37 59 89 48 84 64 99 47  9 63 72]
Maximum value: 99
Index of maximum value: 15


In [21]:
# Given two NumPy arrays: import numpy as np arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8]) Compute the element-wise product of the two arrays

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

elementwise_product = arr1 * arr2
print("Element-wise product:", elementwise_product)

Element-wise product: [ 5 12 21 32]


In [6]:
# Write a Pandas program to add, subtract, multiple and divide two Pandas Series. Input: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

import pandas as pd

data1 = [2, 4, 6, 8, 10]
data2 = [1, 3, 5, 7, 9]

series1 = pd.Series(data1)
series2 = pd.Series(data2)

add_result = series1 + series2
sub_result = series1 - series2
mul_result = series1 * series2
div_result = series1 / series2

results = pd.DataFrame({
    "Series1": series1,
    "Series2": series2,
    "Addition": add_result,
    "Subraction": sub_result,
    "Multiplication": mul_result,
    "Division": div_result
})

results


Series1  Series2  Addition  Subraction  Multiplication  Division
0        2        1         3           1               2  2.000000
1        4        3         7           1              12  1.333333
2        6        5        11           1              30  1.200000
3        8        7        15           1              56  1.142857
4       10        9        19           1              90  1.111111

In [16]:
# Create a Pandas DataFrame from the following dictionary, where the keys represent columns and the values represent the data: data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28], 'City': ['New York', 'London', 'Paris', 'Tokyo']}

data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28], 'City': ['New York', 'London', 'Paris', 'Tokyo']}

Person = pd.DataFrame(data)

Person

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo

In [18]:
# Given a Pandas DataFrame 'df', select the first 5 rows of the DataFrame.

data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David','John','Alex'], 'Age': [25, 30, 22, 28, 24, 26], 'City': ['New York', 'London', 'Paris', 'Tokyo','New Jersey','London']}

df = pd.DataFrame(data)

df.head()

Name  Age        City
0    Alice   25    New York
1      Bob   30      London
2  Charlie   22       Paris
3    David   28       Tokyo
4     John   24  New Jersey

In [19]:
# Create a new column 'Salary' in the DataFrame 'df' with random integer values between 50000 and 80000 (inclusive).
import numpy as np


df["Salary"] = np.random.randint(50000, 80001, size = len(df))

df

Name  Age        City  Salary
0    Alice   25    New York   66216
1      Bob   30      London   57456
2  Charlie   22       Paris   77801
3    David   28       Tokyo   61594
4     John   24  New Jersey   54251
5     Alex   26      London   56072

In [4]:
# Given two Pandas DataFrames 'df1' and 'df2' with the same columns, concatenate them vertically.
import pandas as pd

data1 = {'Name': ['Alice', 'Bob', 'Charlie'],
         'Age': [25, 30, 22]}

data2 = {'Name': ['David', 'Eve', 'Frank'],
         'Age': [28, 24, 29]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

data_concat = pd.concat([df1,df2], axis = 0)

data_concat

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
0    David   28
1      Eve   24
2    Frank   29

In [8]:
# Create a new DataFrame named 'df_filtered' from 'df', containing only rows where the 'Age' column is greater than 25.

data_concat

df_filtered = data_concat[data_concat["Age"]>25]

df_filtered

Name  Age
1    Bob   30
0  David   28
2  Frank   29

In [13]:
# Given a Pandas DataFrame 'df', sort the DataFrame based on the 'Age' column in ascending order.

df_filtered

df_sorted = df_filtered.sort_values(by = "Age")

df_sorted

Name  Age
0  David   28
2  Frank   29
1    Bob   30

In [22]:
# Calculate the mean and median of the 'Salary' column in the DataFrame 'df'.

mean_salary = df["Salary"].mean()
median_salary = df["Salary"].median()

print("Mean_Salary:", mean_salary)
print("Median_Salary:", median_salary)

Mean_Salary: 62231.666666666664
Median_Salary: 59525.0


In [27]:
# Group the DataFrame 'df' by the 'City' column and calculate the mean 'Age' for each group.

df

age_mean_by_city = df.groupby("City")['Age'].mean()

age_mean_by_city

City
London        28.0
New Jersey    24.0
New York      25.0
Paris         22.0
Tokyo         28.0
Name: Age, dtype: float64

In [29]:
# Read the csv provide(nba.csv) into a Dataframe- 
# Display: *Number of rows and columns in dataframe 
# * Top 10 and bottom 10 rows 
# * Summary statistics for numerical columns 
# *Datatype of columns in dataframe 
# * Length of the data 
# * Print all the Rows from index 100 to 200

df = pd.read_csv("nba.csv")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display top 10 rows
print("Top 10 rows:")
print(df.head(10))

# Display bottom 10 rows
print("Bottom 10 rows:")
print(df.tail(10))

# Summary statistics for numerical columns
print("Summary statistics for numerical columns:")
print(df.describe())

# Datatype of columns in the DataFrame
print("Datatype of columns:")
print(df.dtypes)

# Length of the data
print("Length of the data:", len(df))

# Print all rows from index 100 to 200
print("Rows from index 100 to 200:")
print(df.iloc[100:201])

Number of rows: 457
Number of columns: 8
Top 10 rows:
            Name            Team  Number Position  Age  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25     180   
1    Jae Crowder  Boston Celtics      99       SF   25     235   
2   John Holland  Boston Celtics      30       SG   27     205   
3    R.J. Hunter  Boston Celtics      28       SG   22     185   
4  Jonas Jerebko  Boston Celtics       8       PF   29     231   
5   Amir Johnson  Boston Celtics      90       PF   29     240   
6  Jordan Mickey  Boston Celtics      55       PF   21     235   
7   Kelly Olynyk  Boston Celtics      41        C   25     238   
8   Terry Rozier  Boston Celtics      12       PG   22     190   
9   Marcus Smart  Boston Celtics      36       PG   22     220   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5        